# node.js.yml -- GitHub Actions workflow to test a NodeJS app.
#
# This workflow contains jobs for:
# * test (`jest`)
# * lint (`eslint`)
# * type-check (`tsc`)
#
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test and lint

on:
  push:
    branches: [ "main", "v[0-9]+.[0-9]+.x", "v[0-9]+.x" ]
  pull_request:
    branches: [ "main", "v[0-9]+.[0-9]+.x", "v[0-9]+.x" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    # Start the server, runs tests, then kill the background job (hopefully)
    # At the very least, it'll die once the workflow ends
    - name: Run test suite
      run: npm start & (sleep 3 && npm test && (jobs -p | xargs -I{} kill -- -{}))

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - name: Run linting
      run: npm run lint

  type-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - run: npm ci
    - name: Run type-checking
      run: npm run tsc
